<div id="oldHtml" class="oldHtml"><div id="oldHtml-2" class="oldHtml"><div data-gjs="navbar" id="i4bt" class="navbar"><div id="ib6g" class="navbar-container"><a href="/" class="navbar-brand"></a><div data-gjs="navbar-items" class="navbar-items-c"><nav data-gjs="navbar-menu" id="i2bg" class="navbar-menu"><a href="http://localhost/dashboard/saltanb/public/cms/pages" class="navbar-menu-link">Admin</a></nav></div><div id="i3ia" class="navbar-burger"><div class="navbar-burger-line">
            </div><div class="navbar-burger-line">
            </div><div class="navbar-burger-line">
            </div></div></div></div><div id="ixnal" class="row"><div id="iq9pa" class="cell"><div class="navbar1"><div class="subnav1"><button class="subnavbtn1">About Us <i class="fa fa-caret-down">
                    </i></button><div class="subnav-content1"><a href="http://localhost/dashboard/saltanb/public/pages/our_mission" class="clicker">Our Mission</a><a href="http://localhost/dashboard/saltanb/public/pages/our_story">Our Story</a><a href="http://localhost/dashboard/saltanb/public/pages/our_client">Our Client</a><a href="http://localhost/dashboard/saltanb/public/pages/job_opportunities">Job Opportunities</a><a href="http://localhost/dashboard/saltanb/public/pages/contact">Contact</a></div></div><div class="subnav1"><button class="subnavbtn1">Product <i class="fa fa-caret-down">
                    </i></button><div class="subnav-content1"><a href="http://localhost/dashboard/saltanb/public/pages/smart_seeding_machine">Smart Seeding Machine</a><a href="http://localhost/dashboard/saltanb/public/pages/smart_green_house">Smart Green House</a><a href="http://localhost/dashboard/saltanb/public/pages/growth_measurement_device">Growth Measurement Device</a><a href="http://localhost/dashboard/saltanb/public/pages/smart_iot_platform">Smart IoT Platform</a><a href="http://localhost/dashboard/saltanb/public/pages/smart_decision_support_system">Smart Decision Support System</a></div></div><div class="subnav1"><div class="subnav-content1"><a href="http://localhost/dashboard/saltanb/public/pages/smart_farm_construction">Smart Farm Construction</a></div></div><div class="subnav1"><button class="subnavbtn1">Community <i class="fa fa-caret-down">
                    </i></button><div class="subnav-content1"><a href="../community/public-notice.html">Public Notice</a><a href="../community/farm-new.html">Smart Farm News</a><a href="../community/Q-A.html">Q&A</a></div></div></div><div><div class="sidenav"><a href="#" id="i6vc4">About Us</a><a href="http://localhost/dashboard/saltanb/public/pages/our_mission">Our Mission</a><a href="http://localhost/dashboard/saltanb/public/pages/our_story">Our Story</a><a href="http://localhost/dashboard/saltanb/public/pages/our_client">Our Client</a><a href="http://localhost/dashboard/saltanb/public/pages/job_opportunities">Jobs Opportunities</a><a href="http://localhost/dashboard/saltanb/public/pages/contact">Contact</a></div><div id="hiddendiv"><h1 id="ic616" class="h1">Our Mission</h1><h1>Contact</h1><iframe frameborder="0" id="i5uz2" src="https://maps.google.com/maps?&q=phố đi bộ Bùi Viện, quận 1&z=15&t=q&output=embed"></iframe><div class="ixz9d2"><h2>Busines Solution</h2><i class="fas fa-phone-square-alt"> 82-53-964-0884</i> <br/> <br/><i class="fas fa-envelope"> terius331@saltware.co.kr
                    </i> <br/><h2>Service Consulting
                    </h2><i class="fas fa-phone-square-alt"> 82-53-964-0884</i> <br/> <br/><i class="fas fa-envelope">
                        cbkim@saltware.co.kr
                    </i></div></div></div></div></div><div id="ilfzj" class="row"><div id="ivlce" class="cell"><div data-gjs="navbar" id="if5xv" class="navbar"><div id="izpxf" class="navbar-container"><a href="/" class="navbar-brand"></a><div data-gjs="navbar-items" class="navbar-items-c01"><nav data-gjs="navbar-menu" id="iants" class="navbar-menu"><a href="#" class="navbar-menu-link">About</a><a href="#" class="navbar-menu-link">Newsroom</a><a href="#" class="navbar-menu-link">Related Sites</a></nav></div><div id="i9gh7" class="navbar-burger"><div class="navbar-burger-line">
                    </div><div class="navbar-burger-line">
                    </div><div class="navbar-burger-line">
                    </div></div></div></div><div id="i1rlj"><p draggable="true" id="i6ycs-2-2-2-2"><span draggable="true" id="ijcc8-2-2-2-2">Salta&b</span><span draggable="true" id="ilx23-2-2-2-2"> 301, S Tower, 14, </span><span draggable="true" id="il7fg-2-2-2-2">innovalley-ro</span><span draggable="true" id="ifhvj-2-2-2-2">
                    36-gil, Dong-</span><span draggable="true" id="iub9y-2-2-2-2">gu</span><span draggable="true" id="igb6o-2-2-2-2">,
                    Daegu, Korea</span></p><p draggable="true" id="inf28-2-2-2-2"><span draggable="true" id="ifsqi-2-2-2-2">COPYRIGHT ⓒ </span><span draggable="true" id="isku5-2-2-2-2">Salta&b</span><span draggable="true" id="itmpx-2-2-2-2"> Co.,
                    Ltd. All Rights Reserved.</span></p></div></div></div></div></div>